### ISSUE TITLE
[Bug]: easegress-server --signal-upgrade=true panic

### ISSUE THREAD

**Issue by cyrnicolase** [easegress-io/easegress#1170]
- Easegress v2.6.4
- 22.04.1-Ubuntu x86_64

---

When I reload the easegress-server with command `easegress-server --signal-upgrade=true`. It will panic.

```
panic: close of closed channel

goroutine 1 [running]:
github.com/megaease/easegress/v2/pkg/api.(*dynamicMux).close(...)
        github.com/megaease/easegress/v2/pkg/api/dynamicmux.go:139
github.com/megaease/easegress/v2/pkg/api.(*Server).Close(0xc000401900, 0x0?)
        github.com/megaease/easegress/v2/pkg/api/server.go:131 +0x111
github.com/megaease/easegress/v2/cmd.RunServer()
        github.com/megaease/easegress/v2/cmd/server.go:142 +0x78a
main.main()
        github.com/megaease/easegress/v2/cmd/server/main.go:27 +0x17
```

**Comment by suchen-sci** [comment]
Hi, thanks for you report, we will check what happens here...

**Comment by xxx7xxxx** [comment]
Fixed
